import Avatar from "./Avatar"
import Button from "./Button"
import Card from "./Card"
import Footer from "./Footer"
import Heading from "./Heading"
import { Input } from "./Input"
import LoaderForDashboard from "./LoaderForDashboard"
import LoginScelton from "./LoginScelton"
import SubHeading from "./SubHeading"
import SendMoneyLoader from "./SendMoneyLoader"
import LoaderForUpdateInfo from "./LoaderForUpdateInfo"
import LoaderForHistory from "./LoaderForHistory"
export { LoaderForHistory, SendMoneyLoader, LoaderForUpdateInfo, Avatar, Button, Card, Footer, Heading, Input, LoaderForDashboard, LoginScelton, SubHeading }